version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    restart: on-failure
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: on-failure
