version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    restart: on-failure
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: on-failure
